name: Java CI with Gradle

on:
  push:
    branches: [ "dev/dev_anseongjin" ]
  pull_request:
    branches: [ "dev/dev_anseongjin" ]

permissions:
  id-token: write   # This is required for requesting the JWT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: saas-oil-application-jar
          path: target/*.jar

      - name: List files in the working directory - 1
        run: ls target/

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: saas-oil-application-jar
          path: target/

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::794187215716:role/saas-git-action
          role-session-name: ecrRoleSession
          aws-region: ap-northeast-2

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build . -t 794187215716.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.SEONGJIN_DOCKER_REPO }}:tag-${{ github.sha }}

      # 이미지를 ECR에 푸시
      - name: Push Docker image to AWS ECR
        run: docker push 794187215716.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.SEONGJIN_DOCKER_REPO }}:tag-${{ github.sha }}