name: Hyeongwon workflows

on:
  push:
    branches: [ "dev_hyeongwon" ]
  pull_request:
    branches: [ "dev_hyeongwon" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: saas-oil-application-jar
          path: target/*.jar

  push-docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: saas-oil-application-jar
          path: target/

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t saas-oil-application:release-dev_hyeongwon-${{ github.sha }} .

      # Docker Hub에 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HYEONGWON_DOCKER_USERNAME }}
          password: ${{ secrets.HYEONGWON_DOCKER_PASSWORD }}

      # 이미지를 Docker 재태그 및 Hub에 푸시
      - name: Push Docker image to DockerHub
        run: |
          docker tag saas-oil-application:release-dev_hyeongwon-${{ github.sha }} yosigoon/saas-oil:saas-oil-application-release-dev_hyeongwon-${{ github.sha }}
          docker push yosigoon/saas-oil:saas-oil-application-release-dev_hyeongwon-${{ github.sha }}
  

  update-deployment:
    needs: push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout saas-kubernetes repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.HYEONGWON_GITHUB_TOKEN }}
          repository: 'saas-in-the-well/saas-kubernetes'
          ref: 'main'

      # 쿠버네티스 배포이미지 업데이트
      - name: Update Kubernetes Deployment Image
        run: |
          sed -i 's|yosigoon/saas-oil:saas-oil-application|yosigoon/saas-oil:saas-oil-application-release-dev_hyeongwon-${{ github.sha }}|' ./kube/hyeongwon/deployment.yaml
          git config --global user.name "HW_GithubAction"
          git config --global user.email "yosigoon@gmail.com"
          git add ./kube/hyeongwon/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push